FROM node:lts as build

WORKDIR /usr/src/app
COPY package.json yarn.lock ./
RUN yarn install --non-interactive --frozen-lockfile --ignore-scripts

COPY packages/simpleserialize.com .
RUN yarn install --non-interactive --ignore-scripts
RUN yarn build

FROM nginx:alpine
COPY --from=build /usr/src/app/dist /usr/share/nginx/html
EXPOSE 80
