// Since wasm binary data cannot be statically imported into javascript,
// we preprocess the binary data into valid javascript code, a single exportable object.
// which can be statically imported.

import fs from "node:fs";

interface BinaryMeta {
  input: string;
  exportName: string;
}

const binaries: BinaryMeta[] = [
  {
    input: "build/optimized.simd.wasm",
    exportName: "wasmSimdCode",
  },
  {
    input: "build/optimized.wasm",
    exportName: "wasmCode",
  },
];

for (const {input, exportName} of binaries) {
  const wasmBinary = Uint8Array.from(fs.readFileSync(input));

  const outputString = `// This file was autogenerated by scripts/codegen.ts
// DO NOT modify this file by hand!

// biome-ignore format:
export const ${exportName} = Uint8Array.from([${wasmBinary.toString()}]);
`;

  fs.writeFileSync(`src/${exportName}.ts`, outputString);
}
