name: "Run the tests with multi-runtime"
description: "Run tests with multiple runtime"
inputs:
  runtime:
    description: Select runtime
    required: true

runs:
  using: "composite"
  steps:
    - name: Select nodejs runtime
      if: inputs.runtime == 'nodejs'
      run: echo "TEST_COMMAND=yarn" >> $GITHUB_ENV      
      shell: bash


    - name: Select bun runtime
      if: inputs.runtime == 'bun'    
      run: echo "TEST_COMMAND=bun run --bun" >> $GITHUB_ENV
      shell: bash

    - name: Select deno runtime
      if: inputs.runtime == 'deno'    
      run: echo "TEST_COMMAND=deno run -A --unstable-sloppy-imports" >> $GITHUB_ENV
      shell: bash

    - name: Unit Tests
      run: ${{env.TEST_COMMAND}} test
      shell: bash

    - name: Browsers Tests
      if: inputs.runtime == 'nodejs'
      run: ${{env.TEST_COMMAND}} test:browsers
      shell: bash

    - name: Restore spec tests cache
      uses: actions/cache@master
      with:
        path: packages/ssz/spec-tests
        key: spec-test-data-${{ hashFiles('packages/ssz/test/specTestVersioning.ts') }}

    - name: Download spec tests
      if: inputs.runtime == 'deno'
      run: yarn download-spec-tests
      working-directory: packages/ssz
      shell: bash

    - name: Download spec tests
      if: inputs.runtime == 'bun'
      run: bun run --bun test/spec/downloadTests.ts
      working-directory: packages/ssz
      shell: bash

    - name: Download spec tests
      if: inputs.runtime == 'nodejs'
      run: ${{env.TEST_COMMAND}} download-spec-tests
      working-directory: packages/ssz
      shell: bash

    - name: Spec tests general
      run: ${{env.TEST_COMMAND}} test:spec-generic
      working-directory: packages/ssz
      shell: bash

    - name: Spec tests phase0-minimal
      run: LODESTAR_FORK=phase0 ${{env.TEST_COMMAND}} test:spec-static-minimal
      working-directory: packages/ssz
      shell: bash

    - name: Spec tests phase0-mainnet
      run: LODESTAR_FORK=phase0 ${{env.TEST_COMMAND}} test:spec-static-mainnet
      working-directory: packages/ssz
      shell: bash

    - name: Spec tests altair-minimal
      run: LODESTAR_FORK=altair ${{env.TEST_COMMAND}} test:spec-static-minimal
      working-directory: packages/ssz
      shell: bash

    - name: Spec tests altair-mainnet
      run: LODESTAR_FORK=altair ${{env.TEST_COMMAND}} test:spec-static-mainnet
      working-directory: packages/ssz
      shell: bash

    - name: Spec tests bellatrix-minimal
      run: LODESTAR_FORK=bellatrix ${{env.TEST_COMMAND}} test:spec-static-minimal
      working-directory: packages/ssz
      shell: bash

    - name: Spec tests bellatrix-mainnet
      run: LODESTAR_FORK=bellatrix ${{env.TEST_COMMAND}} test:spec-static-mainnet
      working-directory: packages/ssz
      shell: bash