name: Benchmark

# only one can tun at a time.
# Actions access a common cache entry and may corrupt it.
concurrency: cd-benchmark-${{ github.ref }}

on:
  push:
    branches:
      - master
      - benchmark # For debugging
  pull_request:
    branches:
      - master

jobs:
  benchmark:
    runs-on: ubuntu-latest
    # Don't run on forks. Forks don't have access to the S3 credentials and the workflow will fail
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: yarn && yarn build

      - name: Run benchmarks
        run: yarn benchmark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # benchmark options
          BENCHMARK_S3: true
          # S3 credentials
          S3_ACCESS_KEY: ${{ secrets.S3_BENCH_LODESTAR_ACCESS_KEY }}
          S3_SECRET_KEY: ${{ secrets.S3_BENCH_LODESTAR_SECRET_KEY }}
          S3_REGION: ${{ secrets.S3_BENCH_LODESTAR_REGION }}
          S3_BUCKET: ${{ secrets.S3_BENCH_LODESTAR_BUCKET }}
          S3_ENDPOINT: ${{ secrets.S3_BENCH_LODESTAR_ENDPOINT }}
          # Key prefix to separate benchmark data from multiple repositories
          S3_KEY_PREFIX: ${{ github.repository }}/${{ runner.os }}
