name: Tests

on: [pull_request, push]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Bootstrap
        run: yarn
      - name: Check types
        run: yarn check-types
      - name: Build
        run: yarn build
      - name: Lint
        run: yarn lint
      - name: Tests
        run: yarn test
      - name: Download spec tests
        run: yarn download-spec-tests
      - name: Spec tests
        run: yarn test:spec
